### PR TITLE
WIP: TumbleBit UI

### PR DESCRIPTION
**Pull request by DanGould**
The goal is to be able to start a tumble from within the TumbleBit menu tab. User needs to input a few details to get going.

1. Destination. For mvp, input of an output address is good. Validate the address if possible. v2 the destination could be selected from one of a user's Breeze wallets in a dropdown with an option for  manual address input.

2. TumblerServer selection. This address may be hard coded to start to a Stratis testnet tumbler. v2 should accept an address via text input. v3 could maybe have a nice server explorer auto populated by exploring the stratis blockchain for tumbler registrations. Keeping fees/tumbler registration tied to stratis is be best for the business. Thinking something like this, obviously less detailed

valve server explorer

The explorer will display
  - number of participants
  - epoch denomination
  - epoch tumbler fee (% is more clear than absolute, display both)
  - tumbler server location (if made publicly available as a TumblerServerParameter. Everything is onion routed, after all)
  - time estimation to tumble contents of one's wallet (maybe v2)
  - user rating/satisfaction?
  - lifetime number of coins tumbled (this may be possible?)

3. Start/Stop tumble. Should be able to view the status of a tumble here as well. One can monitor balance from the "wallet" screen but this should also display the wallet balance. output of `Interactive.cs` console should be enough for an mvp, it is readable. labeled epochs with progress bars can come later. Once the wallet is out of funds, the user is notified & disconnected from the tumbler.

Selecting the quantity to tumble is not necessary for the MVP because we support multiple wallets in Breeze.

### CODE REVIEW

**Comment by nopara73** [comment]
I actually finished a TB client GUI for HiddenWallet, before I stopped working on it. You can steal ideas from it.  
HiddenWalletTumbleBit1  
HiddenWalletTumbleBit2

**Comment by DanGould** [comment]
Beautiful beautiful @nopara73

**Comment by carlton355** [comment]
Dan, when I build this I get the following:

ERROR in C:/Users/carlt/Documents/DanTest/Breeze/Breeze.UI/src/app/wallet/tumblebit/tumblebit.component.ts (18,3): ',' expected.

Looks like you need a comma after [TumbleBitService]

**Comment by dev0tion** [comment]
Hey guys, ping me when you need a review on the Tumblebit UI code :).

**Comment by dev0tion** [comment]
Closing this because it's heavily outdated

**Pull request closed without merging**
