### PR TITLE
Add CORS service to allow Cross-Origin Requests

### PR DESCRIPTION
**Pull request by dev0tion**
Please review code changes. 
This is to allow requests coming from localhost:4200 (the webpack dev server).
@bokobza @dangershony @nopara73

### CODE REVIEW

**Comment by bokobza** [comment]
@dev0tion Both the webpack dev server (if I understand correctly) and the Api are running on localhost.
is it because there is a difference in the port numbers that it doesn't work?

**Comment by bokobza** [comment]
if that's the case can you try running the webpack thing on localhost:5000 please?

**Comment by dev0tion** [comment]
@bokobza Yes, running on a different port makes it a COR.
The webpack dev server can't run on port 5000 when the API is already running on it.

**Comment by bokobza** [comment]
good stuff :-)

**Pull request merged**
