### PR TITLE
Fixed a the name query parameter for API call wallet/general-info

### PR DESCRIPTION
**Pull request by andrasfuchs**
The name query parameter was incorrectly "walletName".
Also added an example request and response for wallet/general-info.

### CODE REVIEW

**Comment by dev0tion** [comment]
The ApiSpecification document is deprecated and should probably be removed @bokobza?
We have transitioned to swagger instead, check out:
localhost:37220/swagger/ for Bitcoin and localhost:37221/swagger/ for Stratis.

**Comment by bokobza** [comment]
It's not really deprecated, it's just not maintained, as made obvious by @andrasfuchs's PR :-)
Let's keep it in here for now @dev0tion and we can think about whether we want to deprecate it later.

**Comment by andrasfuchs** [comment]
@bokobza @dev0tion Thanks for accepting the pull request.

I've just checked swagger, it looks cool. So, would it be alright if I put some information into the ApiSpecification.md about swagger, postman and API testing in general, or is it totally pointless, because you will discard that document eventually?

Can you confirm that you will keep the REST API interface alive in the future, so I can build a client using the interface?

**Comment by bokobza** [comment]
@dev0tion I vote for keeping the file, as the more documentation we have the better. Also it's easier for devs to start from.
What say you?

**Pull request merged**
