### PR TITLE
Use same System.ValueTuple as full node project

### PR DESCRIPTION
**Pull request by NicolasDorier**
Remove a warning of uncompatible versions between Stratis Node and Breeze

### CODE REVIEW

**Comment by bokobza** [comment]
Thanks Nicolas, that's something I saw yesterday. 
I think it's probably better to actually change the Tuple package on the full node to be 4.3.1, I don't know why a pre-release version was chosen there.
We'd normally only use a pre-release version if there was something in there that we need.
Hope it makes sense. :stuck_out_tongue:

**Comment by NicolasDorier** [comment]
usually when someone use a pre-release, he had real reason to do as you need to explicitely want it.

**Comment by dangershony** [comment]
Hmm I don't think I explicitly needed the pre-release so not sure why it was used.

**Comment by bokobza** [comment]
I think it's probably because when we had the full node as a nuget package we had to tick the pre-release box, and VS remembers this setting. So one of us must have added it by mistake.

**Comment by bokobza** [comment]
I'll close this, we need to fix it on the Full node repo.

**Pull request closed without merging**
