### PR TITLE
Remove annoying blinking cursor from Loading the future

### PR DESCRIPTION
**Pull request by nopara73**
Resolves issue: https://github.com/stratisproject/Breeze/issues/252

### CODE REVIEW

**Comment by dev0tion** [comment]
@nopara73 We are not using the CSS files defined in the components, instead we are using SCSS to do the design.
You can add the CSS line in Breeze.UI/src/scss/_custom.scss
After that run: npm run build:styling, it will generate the new styles.css we are using.

If u need anything ping me on Slack.

**Comment by nopara73** [comment]
@dev0tion I don't succeed.

**Comment by dev0tion** [comment]
@nopara73 shall I do it?

**Comment by nopara73** [comment]
@dev0tion Yes, please. I tried to solve all the UI issues open yesterday and today, but I was only able to do just a small percentage of it

**Comment by dev0tion** [comment]
Done in #271

**Pull request closed without merging**
